package com.akolar.eventproc

import com.akolar.eventproc.consumer.Continent

object Country {

  val continent = Map[String, Continent.Value](
    "AL" -> Continent.Europe,
    "AD" -> Continent.Europe,
    "AM" -> Continent.Europe,
    "AT" -> Continent.Europe,
    "BY" -> Continent.Europe,
    "BE" -> Continent.Europe,
    "BA" -> Continent.Europe,
    "BG" -> Continent.Europe,
    "CH" -> Continent.Europe,
    "CY" -> Continent.Europe,
    "CZ" -> Continent.Europe,
    "DE" -> Continent.Europe,
    "DK" -> Continent.Europe,
    "EE" -> Continent.Europe,
    "ES" -> Continent.Europe,
    "FO" -> Continent.Europe,
    "FI" -> Continent.Europe,
    "FR" -> Continent.Europe,
    "GB" -> Continent.Europe,
    "GE" -> Continent.Europe,
    "GI" -> Continent.Europe,
    "GR" -> Continent.Europe,
    "HU" -> Continent.Europe,
    "HR" -> Continent.Europe,
    "IE" -> Continent.Europe,
    "IS" -> Continent.Europe,
    "IT" -> Continent.Europe,
    "LT" -> Continent.Europe,
    "LU" -> Continent.Europe,
    "LV" -> Continent.Europe,
    "MC" -> Continent.Europe,
    "MK" -> Continent.Europe,
    "MT" -> Continent.Europe,
    "NO" -> Continent.Europe,
    "NL" -> Continent.Europe,
    "PO" -> Continent.Europe,
    "PT" -> Continent.Europe,
    "RO" -> Continent.Europe,
    "RU" -> Continent.Europe,
    "SE" -> Continent.Europe,
    "SI" -> Continent.Europe,
    "SK" -> Continent.Europe,
    "SM" -> Continent.Europe,
    "TR" -> Continent.Europe,
    "UA" -> Continent.Europe,
    "VA" -> Continent.Europe
  )
}
